### ISSUE TITLE
move to Microformats repo

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-uf2#16]
@snarfed @dshanske @willnorris @peterwilsoncc What do you think about moving this plugin to the microformats repo and push it to the WordPress directory, to (perhaps) address a larger (developer) audience?

/cc @tantek

**Comment by tantek** [comment]
Might even make more sense in the indieweb repo: https://github.com/indieweb/ since it's something people should install to help make their WordPress site more IndieWeb friendly.

**Comment by dshanske** [comment]
I think the Indieweb one would make sense. But it does need an update and some minor tweaks. Currently, for example, if hentry is styled on a theme(which it shouldn't be, but), it messes that up. It needs an appropriate warning in that regard...possibility some compatibility settings to allow it to be more/less aggressive.

**Comment by dshanske** [comment]
And I am in favor of pushing it to .org after that.

**Comment by dshanske** [comment]
@pfefferle Can you arrange for this to be transferred to the Indieweb repo and we'll set up the review changes options set up on the other Indieweb projects?

**Comment by miklb** [comment]
I second @dshanske request to move.

**Comment by pfefferle** [comment]
Just read about the plan to move all microformats parsers to the microformats repo... does it still make no sense to move this plugin too?

**Comment by tw2113** [comment]
To make sure i'm making sense, this is regarding moving the plugin to https://github.com/microformats/ ownership?

**Comment by dshanske** [comment]
Yes
