### ISSUE TITLE
Propose Name Change

### ISSUE THREAD

**Issue by miklb** [indieweb/wordpress-uf2#19]
Would it be considered to change the name of the plugin to something beginner friendly?

Something along the lines of mf2 theme helper rather than just uf2?

I realize this was created several years ago, and perhaps uf2 was more popular in shorthand for microformats2, but seems mf2 is more widely used now and adding "theme helper" or something similar would give more context to what it does.

**Comment by pfefferle** [comment]
I would not rename the classes but I also support a name change for the readme https://github.com/pfefferle/wordpress-uf2/commit/71a9cbac1be73244f2b3ba70b0d0f7dc4244e07b#commitcomment-22605242

**Comment by pfefferle** [comment]
@miklb is this OK for you?

**Comment by miklb** [comment]
ah, yes.
