### ISSUE TITLE
consistent naming

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-uf2#21]
We should be more consistent with the title... sometimes it is `microformats2`, sometimes it is `Microformats 2` and sometime it is `microformats v2`.

I would prefer `Microformats 2`...

We then have to rename the files, because WordPress uses the plugin name (used in the main plugin file) for the repo and for the slug.

**Comment by dshanske** [comment]
That is fine. So, the slug will be microformats2, and the name will be Microformats 2 ? I want to add detail to the README anyway.

**Comment by pfefferle** [comment]
i think it is `microformats-2` but I will re-check...

**Comment by dshanske** [comment]
I sent a PR. You can modify

**Comment by pfefferle** [comment]
ok, now it's neither `uf2` nor `microformats-2`... the slug is now `wp-uf2`... don't ask...
