### ISSUE TITLE
WP.org version

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-uf2#22]
I submitted the actual version to the WP.org repo because the process can take a while. There are currently 444 plugins in the cue. The WP.org repo is using the name of the plugin as slug, so we might rename some files: https://github.com/indieweb/wordpress-uf2/issues/21

**Comment by pfefferle** [comment]
WP.org repo is generated https://wordpress.org/plugins/wp-uf2/

I will add the 1.0.0 version if my PR is merged: https://github.com/indieweb/wordpress-uf2/pull/24

**Comment by miklb** [comment]
@pfefferle what needs to be done now?

**Comment by pfefferle** [comment]
there are still some glitches... merge request coming... perhaps you also can have a final look!

**Comment by miklb** [comment]
done! Hopefully we can get this in the repo for this weekend, and add it to IndieWeb plugin as well.

**Comment by dshanske** [comment]
Resolved now
