### ISSUE TITLE
Plugin causes spurious HTML to be visible 

### ISSUE THREAD

**Issue by devilgate** [indieweb/wordpress-uf2#31]
With the Microformats 2 plugin active on a self-hosted WordPress instance using the Minnow theme, HTML is visible around the author name on every post. 

I haven't tested it with any other themes.

The attached screenshot shows the issue.

![screen shot 2017-07-20 at 19 18 11](https://user-images.githubusercontent.com/4842280/28432580-4ca6c76e-6d80-11e7-8ae5-d6374428aaf5.png)

**Comment by pfefferle** [comment]
thanks for reporting this issue, but this is heavily theme dependent. some themes are escaping data like the author name and that's why you see the html. i am not sure if it is possible to "fix" this behavior.

**Comment by dshanske** [comment]
Resolved via #37 with setting to disable
